services:
  postgres:
    image: postgres:16-alpine
    container_name: smart-vehicle-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_vehicle_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smart_vehicle_postgres_data:/var/lib/postgresql/data

volumes:
  smart_vehicle_postgres_data:
